from django import forms
from django.contrib.auth.forms import User
from crowdsourcing.models import Task, OCRTranscription, OCRVerification, CrowdsourceVerification
from crowdsourcing.models import NamingTranscription1, NamingTranscription2
from django.forms import ModelForm

class Task_OCRTranscription(forms.ModelForm):
    class Meta:
        model = OCRTranscription
        fields = '__all__'

    ocr_1 = forms.CharField(max_length=10)
    ocr_2 = forms.CharField(max_length=10)
    ocr_3 = forms.CharField(max_length=10)
    ocr_4 = forms.CharField(max_length=10)
    ocr_5 = forms.CharField(max_length=10)
    ocr_6 = forms.CharField(max_length=10)
    ocr_7 = forms.CharField(max_length=10)
    ocr_8 = forms.CharField(max_length=10)
    ocr_9 = forms.CharField(max_length=10)
    ocr_10 = forms.CharField(max_length=10)
    ocr_11 = forms.CharField(max_length=10)
    ocr_12 = forms.CharField(max_length=10)
    ocr_13 = forms.CharField(max_length=10)
    ocr_14 = forms.CharField(max_length=10)
    ocr_15 = forms.CharField(max_length=10)
    ocr_16 = forms.CharField(max_length=10)
    ocr_17 = forms.CharField(max_length=10)
    ocr_18 = forms.CharField(max_length=10)


class Task_OCRVerification(forms.ModelForm):
    class Meta:
        model = OCRVerification
        fields = '__all__'

    ocr_1 = forms.BooleanField(required=False)
    ocr_2 = forms.BooleanField(required=False)
    ocr_3 = forms.BooleanField(required=False)
    ocr_4 = forms.BooleanField(required=False)
    ocr_5 = forms.BooleanField(required=False)
    ocr_6 = forms.BooleanField(required=False)
    ocr_7 = forms.BooleanField(required=False)
    ocr_8 = forms.BooleanField(required=False)
    ocr_9 = forms.BooleanField(required=False)
    ocr_10 = forms.BooleanField(required=False)
    ocr_11 = forms.BooleanField(required=False)
    ocr_12 = forms.BooleanField(required=False)
    ocr_13 = forms.BooleanField(required=False)
    ocr_14 = forms.BooleanField(required=False)
    ocr_15 = forms.BooleanField(required=False)
    ocr_16 = forms.BooleanField(required=False)
    ocr_17 = forms.BooleanField(required=False)
    ocr_18 = forms.BooleanField(required=False)


class Task_CrowdsourceVerification(forms.ModelForm):
    class Meta:
        model = CrowdsourceVerification
        fields = '__all__'

    ocr_1 = forms.BooleanField(required=False)
    ocr_2 = forms.BooleanField(required=False)
    ocr_3 = forms.BooleanField(required=False)
    ocr_4 = forms.BooleanField(required=False)
    ocr_5 = forms.BooleanField(required=False)
    ocr_6 = forms.BooleanField(required=False)
    ocr_7 = forms.BooleanField(required=False)
    ocr_8 = forms.BooleanField(required=False)
    ocr_9 = forms.BooleanField(required=False)
    ocr_10 = forms.BooleanField(required=False)
    ocr_11 = forms.BooleanField(required=False)
    ocr_12 = forms.BooleanField(required=False)
    ocr_13 = forms.BooleanField(required=False)
    ocr_14 = forms.BooleanField(required=False)
    ocr_15 = forms.BooleanField(required=False)
    ocr_16 = forms.BooleanField(required=False)
    ocr_17 = forms.BooleanField(required=False)
    ocr_18 = forms.BooleanField(required=False)


class Task_NamingTranscription1(forms.ModelForm):
    class Meta:
        model = NamingTranscription1
        fields = '__all__'

    cell_b30 = forms.CharField(max_length=10)
    confidence_b30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"),(2,2),(3,3),(4,4),(5,"5 (Most Confident)")))
    cell_b31 = forms.CharField(max_length=10)
    cell_b32 = forms.CharField(max_length=10)
    cell_b33 = forms.CharField(max_length=10)
    cell_b34 = forms.CharField(max_length=10)
    cell_b35 = forms.CharField(max_length=10)
    cell_b36 = forms.CharField(max_length=10)
    cell_b37 = forms.CharField(max_length=10)
    cell_b38 = forms.CharField(max_length=10)
    cell_b39 = forms.CharField(max_length=10)
    cell_b40 = forms.CharField(max_length=10)
    cell_c30 = forms.CharField(max_length=10)
    cell_c31 = forms.CharField(max_length=10)
    cell_c32 = forms.CharField(max_length=10)
    cell_c33 = forms.CharField(max_length=10)
    cell_c34 = forms.CharField(max_length=10)
    cell_c35 = forms.CharField(max_length=10)
    cell_c36 = forms.CharField(max_length=10)
    cell_c37 = forms.CharField(max_length=10)
    cell_c38 = forms.CharField(max_length=10)
    cell_c39 = forms.CharField(max_length=10)
    cell_c40 = forms.CharField(max_length=10)
    cell_d30 = forms.CharField(max_length=10)
    cell_d31 = forms.CharField(max_length=10)
    cell_d32 = forms.CharField(max_length=10)
    cell_d33 = forms.CharField(max_length=10)
    cell_d34 = forms.CharField(max_length=10)
    cell_d35 = forms.CharField(max_length=10)
    cell_d36 = forms.CharField(max_length=10)
    cell_d37 = forms.CharField(max_length=10)
    cell_d38 = forms.CharField(max_length=10)
    cell_d39 = forms.CharField(max_length=10)
    cell_d40 = forms.CharField(max_length=10)
    cell_e30 = forms.CharField(max_length=10)
    cell_e31 = forms.CharField(max_length=10)
    cell_e32 = forms.CharField(max_length=10)
    cell_e33 = forms.CharField(max_length=10)
    cell_e34 = forms.CharField(max_length=10)
    cell_e35 = forms.CharField(max_length=10)
    cell_e36 = forms.CharField(max_length=10)
    cell_e37 = forms.CharField(max_length=10)
    cell_e38 = forms.CharField(max_length=10)
    cell_e39 = forms.CharField(max_length=10)
    cell_e40 = forms.CharField(max_length=10)
    cell_f30 = forms.CharField(max_length=10)
    cell_f31 = forms.CharField(max_length=10)
    cell_f32 = forms.CharField(max_length=10)
    cell_f33 = forms.CharField(max_length=10)
    cell_f34 = forms.CharField(max_length=10)
    cell_f35 = forms.CharField(max_length=10)
    cell_f36 = forms.CharField(max_length=10)
    cell_f37 = forms.CharField(max_length=10)
    cell_f38 = forms.CharField(max_length=10)
    cell_f39 = forms.CharField(max_length=10)
    cell_f40 = forms.CharField(max_length=10)
    cell_g30 = forms.CharField(max_length=10)
    cell_g31 = forms.CharField(max_length=10)
    cell_g32 = forms.CharField(max_length=10)
    cell_g33 = forms.CharField(max_length=10)
    cell_g34 = forms.CharField(max_length=10)
    cell_g35 = forms.CharField(max_length=10)
    cell_g36 = forms.CharField(max_length=10)
    cell_g37 = forms.CharField(max_length=10)
    cell_g38 = forms.CharField(max_length=10)
    cell_g39 = forms.CharField(max_length=10)
    cell_g40 = forms.CharField(max_length=10)
    cell_h30 = forms.CharField(max_length=10)
    cell_h31 = forms.CharField(max_length=10)
    cell_h32 = forms.CharField(max_length=10)
    cell_h33 = forms.CharField(max_length=10)
    cell_h34 = forms.CharField(max_length=10)
    cell_h35 = forms.CharField(max_length=10)
    cell_h36 = forms.CharField(max_length=10)
    cell_h37 = forms.CharField(max_length=10)
    cell_h38 = forms.CharField(max_length=10)
    cell_h39 = forms.CharField(max_length=10)
    cell_h40 = forms.CharField(max_length=10)
    cell_i30 = forms.CharField(max_length=10)
    cell_i31 = forms.CharField(max_length=10)
    cell_i32 = forms.CharField(max_length=10)
    cell_i33 = forms.CharField(max_length=10)
    cell_i34 = forms.CharField(max_length=10)
    cell_i35 = forms.CharField(max_length=10)
    cell_i36 = forms.CharField(max_length=10)
    cell_i37 = forms.CharField(max_length=10)
    cell_i38 = forms.CharField(max_length=10)
    cell_i39 = forms.CharField(max_length=10)
    cell_i40 = forms.CharField(max_length=10)


class Task_NamingTranscription2(forms.ModelForm):
    class Meta:
        model = NamingTranscription2
        fields = '__all__'

    cell_b30 = forms.CharField(max_length=10)
    cell_b31 = forms.CharField(max_length=10)
    cell_b32 = forms.CharField(max_length=10)
    cell_b33 = forms.CharField(max_length=10)
    cell_b34 = forms.CharField(max_length=10)
    cell_b35 = forms.CharField(max_length=10)
    cell_b36 = forms.CharField(max_length=10)
    cell_b37 = forms.CharField(max_length=10)
    cell_b38 = forms.CharField(max_length=10)
    cell_b39 = forms.CharField(max_length=10)
    cell_b40 = forms.CharField(max_length=10)
    cell_c30 = forms.CharField(max_length=10)
    cell_c31 = forms.CharField(max_length=10)
    cell_c32 = forms.CharField(max_length=10)
    cell_c33 = forms.CharField(max_length=10)
    cell_c34 = forms.CharField(max_length=10)
    cell_c35 = forms.CharField(max_length=10)
    cell_c36 = forms.CharField(max_length=10)
    cell_c37 = forms.CharField(max_length=10)
    cell_c38 = forms.CharField(max_length=10)
    cell_c39 = forms.CharField(max_length=10)
    cell_c40 = forms.CharField(max_length=10)
    cell_d30 = forms.CharField(max_length=10)
    cell_d31 = forms.CharField(max_length=10)
    cell_d32 = forms.CharField(max_length=10)
    cell_d33 = forms.CharField(max_length=10)
    cell_d34 = forms.CharField(max_length=10)
    cell_d35 = forms.CharField(max_length=10)
    cell_d36 = forms.CharField(max_length=10)
    cell_d37 = forms.CharField(max_length=10)
    cell_d38 = forms.CharField(max_length=10)
    cell_d39 = forms.CharField(max_length=10)
    cell_d40 = forms.CharField(max_length=10)
    cell_e30 = forms.CharField(max_length=10)
    cell_e31 = forms.CharField(max_length=10)
    cell_e32 = forms.CharField(max_length=10)
    cell_e33 = forms.CharField(max_length=10)
    cell_e34 = forms.CharField(max_length=10)
    cell_e35 = forms.CharField(max_length=10)
    cell_e36 = forms.CharField(max_length=10)
    cell_e37 = forms.CharField(max_length=10)
    cell_e38 = forms.CharField(max_length=10)
    cell_e39 = forms.CharField(max_length=10)
    cell_e40 = forms.CharField(max_length=10)
    cell_f30 = forms.CharField(max_length=10)
    cell_f31 = forms.CharField(max_length=10)
    cell_f32 = forms.CharField(max_length=10)
    cell_f33 = forms.CharField(max_length=10)
    cell_f34 = forms.CharField(max_length=10)
    cell_f35 = forms.CharField(max_length=10)
    cell_f36 = forms.CharField(max_length=10)
    cell_f37 = forms.CharField(max_length=10)
    cell_f38 = forms.CharField(max_length=10)
    cell_f39 = forms.CharField(max_length=10)
    cell_f40 = forms.CharField(max_length=10)
    cell_g30 = forms.CharField(max_length=10)
    cell_g31 = forms.CharField(max_length=10)
    cell_g32 = forms.CharField(max_length=10)
    cell_g33 = forms.CharField(max_length=10)
    cell_g34 = forms.CharField(max_length=10)
    cell_g35 = forms.CharField(max_length=10)
    cell_g36 = forms.CharField(max_length=10)
    cell_g37 = forms.CharField(max_length=10)
    cell_g38 = forms.CharField(max_length=10)
    cell_g39 = forms.CharField(max_length=10)
    cell_g40 = forms.CharField(max_length=10)
    cell_h30 = forms.CharField(max_length=10)
    cell_h31 = forms.CharField(max_length=10)
    cell_h32 = forms.CharField(max_length=10)
    cell_h33 = forms.CharField(max_length=10)
    cell_h34 = forms.CharField(max_length=10)
    cell_h35 = forms.CharField(max_length=10)
    cell_h36 = forms.CharField(max_length=10)
    cell_h37 = forms.CharField(max_length=10)
    cell_h38 = forms.CharField(max_length=10)
    cell_h39 = forms.CharField(max_length=10)
    cell_h40 = forms.CharField(max_length=10)
    cell_i30 = forms.CharField(max_length=10)
    cell_i31 = forms.CharField(max_length=10)
    cell_i32 = forms.CharField(max_length=10)
    cell_i33 = forms.CharField(max_length=10)
    cell_i34 = forms.CharField(max_length=10)
    cell_i35 = forms.CharField(max_length=10)
    cell_i36 = forms.CharField(max_length=10)
    cell_i37 = forms.CharField(max_length=10)
    cell_i38 = forms.CharField(max_length=10)
    cell_i39 = forms.CharField(max_length=10)
    cell_i40 = forms.CharField(max_length=10)
