from django import forms
from django.contrib.auth.forms import User
from crowdsourcing.models import Task, OCRTranscription, OCRVerification, CrowdsourceVerification
from crowdsourcing.models import NamingTranscription1, NamingTranscription2
from crowdsourcing.models import FociTranscription1, FociTranscription2
# from crowdsourcing.models import FociGridTranscription1, FociGridTranscription2
from django.forms import ModelForm

class Task_OCRTranscription(forms.ModelForm):
    class Meta:
        model = OCRTranscription
        fields = '__all__'

    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    ocr_1 = forms.CharField(max_length=10)
    ocr_2 = forms.CharField(max_length=10)
    ocr_3 = forms.CharField(max_length=10)
    ocr_4 = forms.CharField(max_length=10)
    ocr_5 = forms.CharField(max_length=10)
    ocr_6 = forms.CharField(max_length=10)
    ocr_7 = forms.CharField(max_length=10)
    ocr_8 = forms.CharField(max_length=10)
    ocr_9 = forms.CharField(max_length=10)
    ocr_10 = forms.CharField(max_length=10)
    ocr_11 = forms.CharField(max_length=10)
    ocr_12 = forms.CharField(max_length=10)
    ocr_13 = forms.CharField(max_length=10)
    ocr_14 = forms.CharField(max_length=10)
    ocr_15 = forms.CharField(max_length=10)
    ocr_16 = forms.CharField(max_length=10)
    ocr_17 = forms.CharField(max_length=10)
    ocr_18 = forms.CharField(max_length=10)


class Task_OCRVerification(forms.ModelForm):
    class Meta:
        model = OCRVerification
        fields = '__all__'
    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    ocr_1 = forms.BooleanField(required=False)
    ocr_2 = forms.BooleanField(required=False)
    ocr_3 = forms.BooleanField(required=False)
    ocr_4 = forms.BooleanField(required=False)
    ocr_5 = forms.BooleanField(required=False)
    ocr_6 = forms.BooleanField(required=False)
    ocr_7 = forms.BooleanField(required=False)
    ocr_8 = forms.BooleanField(required=False)
    ocr_9 = forms.BooleanField(required=False)
    ocr_10 = forms.BooleanField(required=False)
    ocr_11 = forms.BooleanField(required=False)
    ocr_12 = forms.BooleanField(required=False)
    ocr_13 = forms.BooleanField(required=False)
    ocr_14 = forms.BooleanField(required=False)
    ocr_15 = forms.BooleanField(required=False)
    ocr_16 = forms.BooleanField(required=False)
    ocr_17 = forms.BooleanField(required=False)
    ocr_18 = forms.BooleanField(required=False)


class Task_CrowdsourceVerification(forms.ModelForm):
    class Meta:
        model = CrowdsourceVerification
        fields = '__all__'

    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    ocr_1 = forms.BooleanField(required=False)
    ocr_2 = forms.BooleanField(required=False)
    ocr_3 = forms.BooleanField(required=False)
    ocr_4 = forms.BooleanField(required=False)
    ocr_5 = forms.BooleanField(required=False)
    ocr_6 = forms.BooleanField(required=False)
    ocr_7 = forms.BooleanField(required=False)
    ocr_8 = forms.BooleanField(required=False)
    ocr_9 = forms.BooleanField(required=False)
    ocr_10 = forms.BooleanField(required=False)
    ocr_11 = forms.BooleanField(required=False)
    ocr_12 = forms.BooleanField(required=False)
    ocr_13 = forms.BooleanField(required=False)
    ocr_14 = forms.BooleanField(required=False)
    ocr_15 = forms.BooleanField(required=False)
    ocr_16 = forms.BooleanField(required=False)
    ocr_17 = forms.BooleanField(required=False)
    ocr_18 = forms.BooleanField(required=False)


class Task_NamingTranscription1(forms.ModelForm):
    class Meta:
        model = NamingTranscription1
        fields = '__all__'

    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    cell_b25 = forms.CharField(max_length=10)
    confidence_b25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c25 = forms.CharField(max_length=10)
    confidence_c25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d25 = forms.CharField(max_length=10)
    confidence_d25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e25 = forms.CharField(max_length=10)
    confidence_e25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f25 = forms.CharField(max_length=10)
    confidence_f25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g25 = forms.CharField(max_length=10)
    confidence_g25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h25 = forms.CharField(max_length=10)
    confidence_h25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i25 = forms.CharField(max_length=10)
    confidence_i25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b26 = forms.CharField(max_length=10)
    confidence_b26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c26 = forms.CharField(max_length=10)
    confidence_c26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d26 = forms.CharField(max_length=10)
    confidence_d26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e26 = forms.CharField(max_length=10)
    confidence_e26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f26 = forms.CharField(max_length=10)
    confidence_f26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g26 = forms.CharField(max_length=10)
    confidence_g26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h26 = forms.CharField(max_length=10)
    confidence_h26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i26 = forms.CharField(max_length=10)
    confidence_i26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b27 = forms.CharField(max_length=10)
    confidence_b27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c27 = forms.CharField(max_length=10)
    confidence_c27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d27 = forms.CharField(max_length=10)
    confidence_d27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e27 = forms.CharField(max_length=10)
    confidence_e27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f27 = forms.CharField(max_length=10)
    confidence_f27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g27 = forms.CharField(max_length=10)
    confidence_g27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h27 = forms.CharField(max_length=10)
    confidence_h27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i27 = forms.CharField(max_length=10)
    confidence_i27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b28 = forms.CharField(max_length=10)
    confidence_b28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c28 = forms.CharField(max_length=10)
    confidence_c28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d28 = forms.CharField(max_length=10)
    confidence_d28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e28 = forms.CharField(max_length=10)
    confidence_e28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f28 = forms.CharField(max_length=10)
    confidence_f28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g28 = forms.CharField(max_length=10)
    confidence_g28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h28 = forms.CharField(max_length=10)
    confidence_h28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i28 = forms.CharField(max_length=10)
    confidence_i28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b29 = forms.CharField(max_length=10)
    confidence_b29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c29 = forms.CharField(max_length=10)
    confidence_c29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d29 = forms.CharField(max_length=10)
    confidence_d29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e29 = forms.CharField(max_length=10)
    confidence_e29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f29 = forms.CharField(max_length=10)
    confidence_f29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g29 = forms.CharField(max_length=10)
    confidence_g29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h29 = forms.CharField(max_length=10)
    confidence_h29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i29 = forms.CharField(max_length=10)
    confidence_i29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b30 = forms.CharField(max_length=10)
    confidence_b30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c30 = forms.CharField(max_length=10)
    confidence_c30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d30 = forms.CharField(max_length=10)
    confidence_d30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e30 = forms.CharField(max_length=10)
    confidence_e30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f30 = forms.CharField(max_length=10)
    confidence_f30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g30 = forms.CharField(max_length=10)
    confidence_g30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h30 = forms.CharField(max_length=10)
    confidence_h30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i30 = forms.CharField(max_length=10)
    confidence_i30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b31 = forms.CharField(max_length=10)
    confidence_b31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c31 = forms.CharField(max_length=10)
    confidence_c31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d31 = forms.CharField(max_length=10)
    confidence_d31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e31 = forms.CharField(max_length=10)
    confidence_e31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f31 = forms.CharField(max_length=10)
    confidence_f31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g31 = forms.CharField(max_length=10)
    confidence_g31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h31 = forms.CharField(max_length=10)
    confidence_h31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i31 = forms.CharField(max_length=10)
    confidence_i31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b32 = forms.CharField(max_length=10)
    confidence_b32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c32 = forms.CharField(max_length=10)
    confidence_c32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d32 = forms.CharField(max_length=10)
    confidence_d32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e32 = forms.CharField(max_length=10)
    confidence_e32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f32 = forms.CharField(max_length=10)
    confidence_f32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g32 = forms.CharField(max_length=10)
    confidence_g32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h32 = forms.CharField(max_length=10)
    confidence_h32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i32 = forms.CharField(max_length=10)
    confidence_i32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b33 = forms.CharField(max_length=10)
    confidence_b33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c33 = forms.CharField(max_length=10)
    confidence_c33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d33 = forms.CharField(max_length=10)
    confidence_d33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e33 = forms.CharField(max_length=10)
    confidence_e33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f33 = forms.CharField(max_length=10)
    confidence_f33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g33 = forms.CharField(max_length=10)
    confidence_g33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h33 = forms.CharField(max_length=10)
    confidence_h33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i33 = forms.CharField(max_length=10)
    confidence_i33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b34 = forms.CharField(max_length=10)
    confidence_b34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c34 = forms.CharField(max_length=10)
    confidence_c34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d34 = forms.CharField(max_length=10)
    confidence_d34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e34 = forms.CharField(max_length=10)
    confidence_e34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f34 = forms.CharField(max_length=10)
    confidence_f34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g34 = forms.CharField(max_length=10)
    confidence_g34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h34 = forms.CharField(max_length=10)
    confidence_h34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i34 = forms.CharField(max_length=10)
    confidence_i34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b35 = forms.CharField(max_length=10)
    confidence_b35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c35 = forms.CharField(max_length=10)
    confidence_c35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d35 = forms.CharField(max_length=10)
    confidence_d35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e35 = forms.CharField(max_length=10)
    confidence_e35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f35 = forms.CharField(max_length=10)
    confidence_f35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g35 = forms.CharField(max_length=10)
    confidence_g35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h35 = forms.CharField(max_length=10)
    confidence_h35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i35 = forms.CharField(max_length=10)
    confidence_i35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b36 = forms.CharField(max_length=10)
    confidence_b36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c36 = forms.CharField(max_length=10)
    confidence_c36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d36 = forms.CharField(max_length=10)
    confidence_d36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e36 = forms.CharField(max_length=10)
    confidence_e36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f36 = forms.CharField(max_length=10)
    confidence_f36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g36 = forms.CharField(max_length=10)
    confidence_g36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h36 = forms.CharField(max_length=10)
    confidence_h36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i36 = forms.CharField(max_length=10)
    confidence_i36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b37 = forms.CharField(max_length=10)
    confidence_b37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c37 = forms.CharField(max_length=10)
    confidence_c37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d37 = forms.CharField(max_length=10)
    confidence_d37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e37 = forms.CharField(max_length=10)
    confidence_e37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f37 = forms.CharField(max_length=10)
    confidence_f37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g37 = forms.CharField(max_length=10)
    confidence_g37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h37 = forms.CharField(max_length=10)
    confidence_h37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i37 = forms.CharField(max_length=10)
    confidence_i37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b38 = forms.CharField(max_length=10)
    confidence_b38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c38 = forms.CharField(max_length=10)
    confidence_c38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d38 = forms.CharField(max_length=10)
    confidence_d38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e38 = forms.CharField(max_length=10)
    confidence_e38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f38 = forms.CharField(max_length=10)
    confidence_f38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g38 = forms.CharField(max_length=10)
    confidence_g38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h38 = forms.CharField(max_length=10)
    confidence_h38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i38 = forms.CharField(max_length=10)
    confidence_i38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b39 = forms.CharField(max_length=10)
    confidence_b39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c39 = forms.CharField(max_length=10)
    confidence_c39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d39 = forms.CharField(max_length=10)
    confidence_d39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e39 = forms.CharField(max_length=10)
    confidence_e39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f39 = forms.CharField(max_length=10)
    confidence_f39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g39 = forms.CharField(max_length=10)
    confidence_g39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h39 = forms.CharField(max_length=10)
    confidence_h39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i39 = forms.CharField(max_length=10)
    confidence_i39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b40 = forms.CharField(max_length=10)
    confidence_b40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c40 = forms.CharField(max_length=10)
    confidence_c40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d40 = forms.CharField(max_length=10)
    confidence_d40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e40 = forms.CharField(max_length=10)
    confidence_e40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f40 = forms.CharField(max_length=10)
    confidence_f40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g40 = forms.CharField(max_length=10)
    confidence_g40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h40 = forms.CharField(max_length=10)
    confidence_h40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i40 = forms.CharField(max_length=10)
    confidence_i40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))



class Task_NamingTranscription2(forms.ModelForm):
    class Meta:
        model = NamingTranscription2
        fields = '__all__'

    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    cell_b25 = forms.CharField(max_length=10)
    confidence_b25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c25 = forms.CharField(max_length=10)
    confidence_c25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d25 = forms.CharField(max_length=10)
    confidence_d25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e25 = forms.CharField(max_length=10)
    confidence_e25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f25 = forms.CharField(max_length=10)
    confidence_f25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g25 = forms.CharField(max_length=10)
    confidence_g25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h25 = forms.CharField(max_length=10)
    confidence_h25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i25 = forms.CharField(max_length=10)
    confidence_i25 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b26 = forms.CharField(max_length=10)
    confidence_b26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c26 = forms.CharField(max_length=10)
    confidence_c26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d26 = forms.CharField(max_length=10)
    confidence_d26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e26 = forms.CharField(max_length=10)
    confidence_e26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f26 = forms.CharField(max_length=10)
    confidence_f26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g26 = forms.CharField(max_length=10)
    confidence_g26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h26 = forms.CharField(max_length=10)
    confidence_h26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i26 = forms.CharField(max_length=10)
    confidence_i26 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b27 = forms.CharField(max_length=10)
    confidence_b27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c27 = forms.CharField(max_length=10)
    confidence_c27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d27 = forms.CharField(max_length=10)
    confidence_d27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e27 = forms.CharField(max_length=10)
    confidence_e27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f27 = forms.CharField(max_length=10)
    confidence_f27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g27 = forms.CharField(max_length=10)
    confidence_g27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h27 = forms.CharField(max_length=10)
    confidence_h27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i27 = forms.CharField(max_length=10)
    confidence_i27 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b28 = forms.CharField(max_length=10)
    confidence_b28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c28 = forms.CharField(max_length=10)
    confidence_c28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d28 = forms.CharField(max_length=10)
    confidence_d28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e28 = forms.CharField(max_length=10)
    confidence_e28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f28 = forms.CharField(max_length=10)
    confidence_f28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g28 = forms.CharField(max_length=10)
    confidence_g28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h28 = forms.CharField(max_length=10)
    confidence_h28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i28 = forms.CharField(max_length=10)
    confidence_i28 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b29 = forms.CharField(max_length=10)
    confidence_b29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c29 = forms.CharField(max_length=10)
    confidence_c29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d29 = forms.CharField(max_length=10)
    confidence_d29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e29 = forms.CharField(max_length=10)
    confidence_e29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f29 = forms.CharField(max_length=10)
    confidence_f29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g29 = forms.CharField(max_length=10)
    confidence_g29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h29 = forms.CharField(max_length=10)
    confidence_h29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i29 = forms.CharField(max_length=10)
    confidence_i29 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b30 = forms.CharField(max_length=10)
    confidence_b30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c30 = forms.CharField(max_length=10)
    confidence_c30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d30 = forms.CharField(max_length=10)
    confidence_d30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e30 = forms.CharField(max_length=10)
    confidence_e30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f30 = forms.CharField(max_length=10)
    confidence_f30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g30 = forms.CharField(max_length=10)
    confidence_g30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h30 = forms.CharField(max_length=10)
    confidence_h30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i30 = forms.CharField(max_length=10)
    confidence_i30 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b31 = forms.CharField(max_length=10)
    confidence_b31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c31 = forms.CharField(max_length=10)
    confidence_c31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d31 = forms.CharField(max_length=10)
    confidence_d31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e31 = forms.CharField(max_length=10)
    confidence_e31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f31 = forms.CharField(max_length=10)
    confidence_f31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g31 = forms.CharField(max_length=10)
    confidence_g31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h31 = forms.CharField(max_length=10)
    confidence_h31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i31 = forms.CharField(max_length=10)
    confidence_i31 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b32 = forms.CharField(max_length=10)
    confidence_b32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c32 = forms.CharField(max_length=10)
    confidence_c32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d32 = forms.CharField(max_length=10)
    confidence_d32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e32 = forms.CharField(max_length=10)
    confidence_e32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f32 = forms.CharField(max_length=10)
    confidence_f32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g32 = forms.CharField(max_length=10)
    confidence_g32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h32 = forms.CharField(max_length=10)
    confidence_h32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i32 = forms.CharField(max_length=10)
    confidence_i32 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b33 = forms.CharField(max_length=10)
    confidence_b33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c33 = forms.CharField(max_length=10)
    confidence_c33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d33 = forms.CharField(max_length=10)
    confidence_d33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e33 = forms.CharField(max_length=10)
    confidence_e33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f33 = forms.CharField(max_length=10)
    confidence_f33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g33 = forms.CharField(max_length=10)
    confidence_g33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h33 = forms.CharField(max_length=10)
    confidence_h33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i33 = forms.CharField(max_length=10)
    confidence_i33 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b34 = forms.CharField(max_length=10)
    confidence_b34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c34 = forms.CharField(max_length=10)
    confidence_c34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d34 = forms.CharField(max_length=10)
    confidence_d34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e34 = forms.CharField(max_length=10)
    confidence_e34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f34 = forms.CharField(max_length=10)
    confidence_f34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g34 = forms.CharField(max_length=10)
    confidence_g34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h34 = forms.CharField(max_length=10)
    confidence_h34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i34 = forms.CharField(max_length=10)
    confidence_i34 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b35 = forms.CharField(max_length=10)
    confidence_b35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c35 = forms.CharField(max_length=10)
    confidence_c35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d35 = forms.CharField(max_length=10)
    confidence_d35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e35 = forms.CharField(max_length=10)
    confidence_e35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f35 = forms.CharField(max_length=10)
    confidence_f35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g35 = forms.CharField(max_length=10)
    confidence_g35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h35 = forms.CharField(max_length=10)
    confidence_h35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i35 = forms.CharField(max_length=10)
    confidence_i35 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b36 = forms.CharField(max_length=10)
    confidence_b36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c36 = forms.CharField(max_length=10)
    confidence_c36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d36 = forms.CharField(max_length=10)
    confidence_d36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e36 = forms.CharField(max_length=10)
    confidence_e36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f36 = forms.CharField(max_length=10)
    confidence_f36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g36 = forms.CharField(max_length=10)
    confidence_g36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h36 = forms.CharField(max_length=10)
    confidence_h36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i36 = forms.CharField(max_length=10)
    confidence_i36 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b37 = forms.CharField(max_length=10)
    confidence_b37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c37 = forms.CharField(max_length=10)
    confidence_c37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d37 = forms.CharField(max_length=10)
    confidence_d37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e37 = forms.CharField(max_length=10)
    confidence_e37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f37 = forms.CharField(max_length=10)
    confidence_f37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g37 = forms.CharField(max_length=10)
    confidence_g37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h37 = forms.CharField(max_length=10)
    confidence_h37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i37 = forms.CharField(max_length=10)
    confidence_i37 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b38 = forms.CharField(max_length=10)
    confidence_b38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c38 = forms.CharField(max_length=10)
    confidence_c38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d38 = forms.CharField(max_length=10)
    confidence_d38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e38 = forms.CharField(max_length=10)
    confidence_e38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f38 = forms.CharField(max_length=10)
    confidence_f38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g38 = forms.CharField(max_length=10)
    confidence_g38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h38 = forms.CharField(max_length=10)
    confidence_h38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i38 = forms.CharField(max_length=10)
    confidence_i38 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b39 = forms.CharField(max_length=10)
    confidence_b39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c39 = forms.CharField(max_length=10)
    confidence_c39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d39 = forms.CharField(max_length=10)
    confidence_d39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e39 = forms.CharField(max_length=10)
    confidence_e39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f39 = forms.CharField(max_length=10)
    confidence_f39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g39 = forms.CharField(max_length=10)
    confidence_g39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h39 = forms.CharField(max_length=10)
    confidence_h39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i39 = forms.CharField(max_length=10)
    confidence_i39 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_b40 = forms.CharField(max_length=10)
    confidence_b40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_c40 = forms.CharField(max_length=10)
    confidence_c40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_d40 = forms.CharField(max_length=10)
    confidence_d40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_e40 = forms.CharField(max_length=10)
    confidence_e40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_f40 = forms.CharField(max_length=10)
    confidence_f40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_g40 = forms.CharField(max_length=10)
    confidence_g40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_h40 = forms.CharField(max_length=10)
    confidence_h40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    cell_i40 = forms.CharField(max_length=10)
    confidence_i40 = forms.ChoiceField(choices=((1,"1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))


class Task_FociTranscription1(forms.ModelForm):
    class Meta:
        model = FociTranscription1
        fields = '__all__'

    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    value_1 = forms.CharField(max_length=10, required=False)
    row_1 = forms.CharField(max_length=10, required=False)
    column_1 = forms.CharField(max_length=10, required=False)
    confidence_1 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_2 = forms.CharField(max_length=10, required=False)
    row_2 = forms.CharField(max_length=10, required=False)
    column_2 = forms.CharField(max_length=10, required=False)
    confidence_2 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_3 = forms.CharField(max_length=10, required=False)
    row_3 = forms.CharField(max_length=10, required=False)
    column_3 = forms.CharField(max_length=10, required=False)
    confidence_3 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_4 = forms.CharField(max_length=10, required=False)
    row_4 = forms.CharField(max_length=10, required=False)
    column_4 = forms.CharField(max_length=10, required=False)
    confidence_4 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_5 = forms.CharField(max_length=10, required=False)
    row_5 = forms.CharField(max_length=10, required=False)
    column_5 = forms.CharField(max_length=10, required=False)
    confidence_5 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_6 = forms.CharField(max_length=10, required=False)
    row_6 = forms.CharField(max_length=10, required=False)
    column_6 = forms.CharField(max_length=10, required=False)
    confidence_6 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_7 = forms.CharField(max_length=10, required=False)
    row_7 = forms.CharField(max_length=10, required=False)
    column_7 = forms.CharField(max_length=10, required=False)
    confidence_7 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_8 = forms.CharField(max_length=10, required=False)
    row_8 = forms.CharField(max_length=10, required=False)
    column_8 = forms.CharField(max_length=10, required=False)
    confidence_8 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_9 = forms.CharField(max_length=10, required=False)
    row_9 = forms.CharField(max_length=10, required=False)
    column_9 = forms.CharField(max_length=10, required=False)
    confidence_9 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_10 = forms.CharField(max_length=10, required=False)
    row_10 = forms.CharField(max_length=10, required=False)
    column_10 = forms.CharField(max_length=10, required=False)
    confidence_10 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))


class Task_FociTranscription2(forms.ModelForm):
    class Meta:
        model = FociTranscription2
        fields = '__all__'

    user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
    value_1 = forms.CharField(max_length=10, required=False)
    row_1 = forms.CharField(max_length=10, required=False)
    column_1 = forms.CharField(max_length=10, required=False)
    confidence_1 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_2 = forms.CharField(max_length=10, required=False)
    row_2 = forms.CharField(max_length=10, required=False)
    column_2 = forms.CharField(max_length=10, required=False)
    confidence_2 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_3 = forms.CharField(max_length=10, required=False)
    row_3 = forms.CharField(max_length=10, required=False)
    column_3 = forms.CharField(max_length=10, required=False)
    confidence_3 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_4 = forms.CharField(max_length=10, required=False)
    row_4 = forms.CharField(max_length=10, required=False)
    column_4 = forms.CharField(max_length=10, required=False)
    confidence_4 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_5 = forms.CharField(max_length=10, required=False)
    row_5 = forms.CharField(max_length=10, required=False)
    column_5 = forms.CharField(max_length=10, required=False)
    confidence_5 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_6 = forms.CharField(max_length=10, required=False)
    row_6 = forms.CharField(max_length=10, required=False)
    column_6 = forms.CharField(max_length=10, required=False)
    confidence_6 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_7 = forms.CharField(max_length=10, required=False)
    row_7 = forms.CharField(max_length=10, required=False)
    column_7 = forms.CharField(max_length=10, required=False)
    confidence_7 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_8 = forms.CharField(max_length=10, required=False)
    row_8 = forms.CharField(max_length=10, required=False)
    column_8 = forms.CharField(max_length=10, required=False)
    confidence_8 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_9 = forms.CharField(max_length=10, required=False)
    row_9 = forms.CharField(max_length=10, required=False)
    column_9 = forms.CharField(max_length=10, required=False)
    confidence_9 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))
    value_10 = forms.CharField(max_length=10, required=False)
    row_10 = forms.CharField(max_length=10, required=False)
    column_10 = forms.CharField(max_length=10, required=False)
    confidence_10 = forms.ChoiceField(choices=((1, "1 (Least Confident)"), (2,2), (3,3), (4,4), (5,"5 (Most Confident)")))


# class Task_FociGridTranscription1(forms.ModelForm):
#     class Meta:
#         model = FociGridTranscription1
#         fields = '__all__'
#
#     user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
#
# class Task_FociGridTranscription2(forms.ModelForm):
#     class Meta:
#         model = FociGridTranscription2
#         fields = '__all__'
#
#     user = forms.CharField(max_length=30, required=False, widget=forms.HiddenInput())
