from django.db import models
from django.template.defaultfilters import slugify

class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, unique=True)
    instructions = models.TextField()
    responses = models.IntegerField(default=0)
    TASK_TYPE_CHOICES = (
        ('T', 'Transcription'),
        ('V', 'Verification'),
    )
    task_type = models.CharField(max_length=1,
                                 choices=TASK_TYPE_CHOICES,
                                 default='T')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

# class Response(models.Model):
#     response_id = models.AutoField(primary_key=True)
#     task = models.ForeignKey(Task)
#     submitted_by = models.CharField(max_length=128)   # models.ForeignKey(User)
#     start_time = models.DateTimeField()
#     end_time = models.DateTimeField()
#     name = models.CharField(max_length=128)
#
#     def __str__(self):
#         return str(self.task) + " - Response #" + str(self.response_id)

class OCRTranscription(models.Model): # 20 fields for the user
    def __str__(self):
        return "OCR Transcription Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'OCR Transcription Response'

    response_id = models.AutoField(primary_key=True, unique=True, default=1)
    ocr_1 = models.CharField(max_length=10)
    ocr_2 = models.CharField(max_length=10)
    ocr_3 = models.CharField(max_length=10)
    ocr_4 = models.CharField(max_length=10)
    ocr_5 = models.CharField(max_length=10)
    ocr_6 = models.CharField(max_length=10)
    ocr_7 = models.CharField(max_length=10)
    ocr_8 = models.CharField(max_length=10)
    ocr_9 = models.CharField(max_length=10)
    ocr_10 = models.CharField(max_length=10)
    ocr_11 = models.CharField(max_length=10)
    ocr_12 = models.CharField(max_length=10)
    ocr_13 = models.CharField(max_length=10)
    ocr_14 = models.CharField(max_length=10)
    ocr_15 = models.CharField(max_length=10)
    ocr_16 = models.CharField(max_length=10)
    ocr_17 = models.CharField(max_length=10)
    ocr_18 = models.CharField(max_length=10)


class OCRVerification(models.Model):
    def __str__(self):
        return "OCR Verification Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'OCR Verification Response'

    response_id = models.AutoField(primary_key=True, unique=True, default=1)
    ocr_1 = models.BooleanField(default=False)
    ocr_2 = models.BooleanField(default=False)
    ocr_3 = models.BooleanField(default=False)
    ocr_4 = models.BooleanField(default=False)
    ocr_5 = models.BooleanField(default=False)
    ocr_6 = models.BooleanField(default=False)
    ocr_7 = models.BooleanField(default=False)
    ocr_8 = models.BooleanField(default=False)
    ocr_9 = models.BooleanField(default=False)
    ocr_10 = models.BooleanField(default=False)
    ocr_11 = models.BooleanField(default=False)
    ocr_12 = models.BooleanField(default=False)
    ocr_13 = models.BooleanField(default=False)
    ocr_14 = models.BooleanField(default=False)
    ocr_15 = models.BooleanField(default=False)
    ocr_16 = models.BooleanField(default=False)
    ocr_17 = models.BooleanField(default=False)
    ocr_18 = models.BooleanField(default=False)


class CrowdsourceVerification(models.Model):
    def __str__(self):
        return "Crowdsource Verification Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Crowdsource Verification Response'

    response_id = models.AutoField(primary_key=True, unique=True, default=1)
    ocr_1 = models.BooleanField(default=False)
    ocr_2 = models.BooleanField(default=False)
    ocr_3 = models.BooleanField(default=False)
    ocr_4 = models.BooleanField(default=False)
    ocr_5 = models.BooleanField(default=False)
    ocr_6 = models.BooleanField(default=False)
    ocr_7 = models.BooleanField(default=False)
    ocr_8 = models.BooleanField(default=False)
    ocr_9 = models.BooleanField(default=False)
    ocr_10 = models.BooleanField(default=False)
    ocr_11 = models.BooleanField(default=False)
    ocr_12 = models.BooleanField(default=False)
    ocr_13 = models.BooleanField(default=False)
    ocr_14 = models.BooleanField(default=False)
    ocr_15 = models.BooleanField(default=False)
    ocr_16 = models.BooleanField(default=False)
    ocr_17 = models.BooleanField(default=False)
    ocr_18 = models.BooleanField(default=False)


class NamingTranscription1(models.Model):
    def __str__(self):
        return "Naming Transcription Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Naming Transcription Response'

    response_id = models.AutoField(primary_key=True, unique=True, default=1)
    cell_b30 = models.CharField(max_length=10)
    confidence_b30 = models.PositiveIntegerField(default=5)
    cell_b31 = models.CharField(max_length=10)
    cell_b32 = models.CharField(max_length=10)
    cell_b33 = models.CharField(max_length=10)
    cell_b34 = models.CharField(max_length=10)
    cell_b35 = models.CharField(max_length=10)
    cell_b36 = models.CharField(max_length=10)
    cell_b37 = models.CharField(max_length=10)
    cell_b38 = models.CharField(max_length=10)
    cell_b39 = models.CharField(max_length=10)
    cell_b40 = models.CharField(max_length=10)
    cell_c30 = models.CharField(max_length=10)
    cell_c31 = models.CharField(max_length=10)
    cell_c32 = models.CharField(max_length=10)
    cell_c33 = models.CharField(max_length=10)
    cell_c34 = models.CharField(max_length=10)
    cell_c35 = models.CharField(max_length=10)
    cell_c36 = models.CharField(max_length=10)
    cell_c37 = models.CharField(max_length=10)
    cell_c38 = models.CharField(max_length=10)
    cell_c39 = models.CharField(max_length=10)
    cell_c40 = models.CharField(max_length=10)
    cell_d30 = models.CharField(max_length=10)
    cell_d31 = models.CharField(max_length=10)
    cell_d32 = models.CharField(max_length=10)
    cell_d33 = models.CharField(max_length=10)
    cell_d34 = models.CharField(max_length=10)
    cell_d35 = models.CharField(max_length=10)
    cell_d36 = models.CharField(max_length=10)
    cell_d37 = models.CharField(max_length=10)
    cell_d38 = models.CharField(max_length=10)
    cell_d39 = models.CharField(max_length=10)
    cell_d40 = models.CharField(max_length=10)
    cell_e30 = models.CharField(max_length=10)
    cell_e31 = models.CharField(max_length=10)
    cell_e32 = models.CharField(max_length=10)
    cell_e33 = models.CharField(max_length=10)
    cell_e34 = models.CharField(max_length=10)
    cell_e35 = models.CharField(max_length=10)
    cell_e36 = models.CharField(max_length=10)
    cell_e37 = models.CharField(max_length=10)
    cell_e38 = models.CharField(max_length=10)
    cell_e39 = models.CharField(max_length=10)
    cell_e40 = models.CharField(max_length=10)
    cell_f30 = models.CharField(max_length=10)
    cell_f31 = models.CharField(max_length=10)
    cell_f32 = models.CharField(max_length=10)
    cell_f33 = models.CharField(max_length=10)
    cell_f34 = models.CharField(max_length=10)
    cell_f35 = models.CharField(max_length=10)
    cell_f36 = models.CharField(max_length=10)
    cell_f37 = models.CharField(max_length=10)
    cell_f38 = models.CharField(max_length=10)
    cell_f39 = models.CharField(max_length=10)
    cell_f40 = models.CharField(max_length=10)
    cell_g30 = models.CharField(max_length=10)
    cell_g31 = models.CharField(max_length=10)
    cell_g32 = models.CharField(max_length=10)
    cell_g33 = models.CharField(max_length=10)
    cell_g34 = models.CharField(max_length=10)
    cell_g35 = models.CharField(max_length=10)
    cell_g36 = models.CharField(max_length=10)
    cell_g37 = models.CharField(max_length=10)
    cell_g38 = models.CharField(max_length=10)
    cell_g39 = models.CharField(max_length=10)
    cell_g40 = models.CharField(max_length=10)
    cell_h30 = models.CharField(max_length=10)
    cell_h31 = models.CharField(max_length=10)
    cell_h32 = models.CharField(max_length=10)
    cell_h33 = models.CharField(max_length=10)
    cell_h34 = models.CharField(max_length=10)
    cell_h35 = models.CharField(max_length=10)
    cell_h36 = models.CharField(max_length=10)
    cell_h37 = models.CharField(max_length=10)
    cell_h38 = models.CharField(max_length=10)
    cell_h39 = models.CharField(max_length=10)
    cell_h40 = models.CharField(max_length=10)
    cell_i30 = models.CharField(max_length=10)
    cell_i31 = models.CharField(max_length=10)
    cell_i32 = models.CharField(max_length=10)
    cell_i33 = models.CharField(max_length=10)
    cell_i34 = models.CharField(max_length=10)
    cell_i35 = models.CharField(max_length=10)
    cell_i36 = models.CharField(max_length=10)
    cell_i37 = models.CharField(max_length=10)
    cell_i38 = models.CharField(max_length=10)
    cell_i39 = models.CharField(max_length=10)
    cell_i40 = models.CharField(max_length=10)

class NamingTranscription2(models.Model):
    def __str__(self):
        return "Naming Transcription (with key) Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Naming Transcription (key) Response'

    response_id = models.AutoField(primary_key=True, unique=True, default=1)
    cell_b30 = models.CharField(max_length=10)
    cell_b31 = models.CharField(max_length=10)
    cell_b32 = models.CharField(max_length=10)
    cell_b33 = models.CharField(max_length=10)
    cell_b34 = models.CharField(max_length=10)
    cell_b35 = models.CharField(max_length=10)
    cell_b36 = models.CharField(max_length=10)
    cell_b37 = models.CharField(max_length=10)
    cell_b38 = models.CharField(max_length=10)
    cell_b39 = models.CharField(max_length=10)
    cell_b40 = models.CharField(max_length=10)
    cell_c30 = models.CharField(max_length=10)
    cell_c31 = models.CharField(max_length=10)
    cell_c32 = models.CharField(max_length=10)
    cell_c33 = models.CharField(max_length=10)
    cell_c34 = models.CharField(max_length=10)
    cell_c35 = models.CharField(max_length=10)
    cell_c36 = models.CharField(max_length=10)
    cell_c37 = models.CharField(max_length=10)
    cell_c38 = models.CharField(max_length=10)
    cell_c39 = models.CharField(max_length=10)
    cell_c40 = models.CharField(max_length=10)
    cell_d30 = models.CharField(max_length=10)
    cell_d31 = models.CharField(max_length=10)
    cell_d32 = models.CharField(max_length=10)
    cell_d33 = models.CharField(max_length=10)
    cell_d34 = models.CharField(max_length=10)
    cell_d35 = models.CharField(max_length=10)
    cell_d36 = models.CharField(max_length=10)
    cell_d37 = models.CharField(max_length=10)
    cell_d38 = models.CharField(max_length=10)
    cell_d39 = models.CharField(max_length=10)
    cell_d40 = models.CharField(max_length=10)
    cell_e30 = models.CharField(max_length=10)
    cell_e31 = models.CharField(max_length=10)
    cell_e32 = models.CharField(max_length=10)
    cell_e33 = models.CharField(max_length=10)
    cell_e34 = models.CharField(max_length=10)
    cell_e35 = models.CharField(max_length=10)
    cell_e36 = models.CharField(max_length=10)
    cell_e37 = models.CharField(max_length=10)
    cell_e38 = models.CharField(max_length=10)
    cell_e39 = models.CharField(max_length=10)
    cell_e40 = models.CharField(max_length=10)
    cell_f30 = models.CharField(max_length=10)
    cell_f31 = models.CharField(max_length=10)
    cell_f32 = models.CharField(max_length=10)
    cell_f33 = models.CharField(max_length=10)
    cell_f34 = models.CharField(max_length=10)
    cell_f35 = models.CharField(max_length=10)
    cell_f36 = models.CharField(max_length=10)
    cell_f37 = models.CharField(max_length=10)
    cell_f38 = models.CharField(max_length=10)
    cell_f39 = models.CharField(max_length=10)
    cell_f40 = models.CharField(max_length=10)
    cell_g30 = models.CharField(max_length=10)
    cell_g31 = models.CharField(max_length=10)
    cell_g32 = models.CharField(max_length=10)
    cell_g33 = models.CharField(max_length=10)
    cell_g34 = models.CharField(max_length=10)
    cell_g35 = models.CharField(max_length=10)
    cell_g36 = models.CharField(max_length=10)
    cell_g37 = models.CharField(max_length=10)
    cell_g38 = models.CharField(max_length=10)
    cell_g39 = models.CharField(max_length=10)
    cell_g40 = models.CharField(max_length=10)
    cell_h30 = models.CharField(max_length=10)
    cell_h31 = models.CharField(max_length=10)
    cell_h32 = models.CharField(max_length=10)
    cell_h33 = models.CharField(max_length=10)
    cell_h34 = models.CharField(max_length=10)
    cell_h35 = models.CharField(max_length=10)
    cell_h36 = models.CharField(max_length=10)
    cell_h37 = models.CharField(max_length=10)
    cell_h38 = models.CharField(max_length=10)
    cell_h39 = models.CharField(max_length=10)
    cell_h40 = models.CharField(max_length=10)
    cell_i30 = models.CharField(max_length=10)
    cell_i31 = models.CharField(max_length=10)
    cell_i32 = models.CharField(max_length=10)
    cell_i33 = models.CharField(max_length=10)
    cell_i34 = models.CharField(max_length=10)
    cell_i35 = models.CharField(max_length=10)
    cell_i36 = models.CharField(max_length=10)
    cell_i37 = models.CharField(max_length=10)
    cell_i38 = models.CharField(max_length=10)
    cell_i39 = models.CharField(max_length=10)
    cell_i40 = models.CharField(max_length=10)
