from django.db import models
from django.template.defaultfilters import slugify

class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, unique=True)
    instructions = models.TextField()
    TASK_TYPE_CHOICES = (
        ('T', 'Transcription'),
        ('V', 'Verification'),
    )
    task_type = models.CharField(max_length=1,
                                 choices=TASK_TYPE_CHOICES,
                                 default='T')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

# class Response(models.Model):
#     response_id = models.AutoField(primary_key=True)
#     task = models.ForeignKey(Task)
#     submitted_by = models.CharField(max_length=128)   # models.ForeignKey(User)
#     start_time = models.DateTimeField()
#     end_time = models.DateTimeField()
#     name = models.CharField(max_length=128)
#
#     def __str__(self):
#         return str(self.task) + " - Response #" + str(self.response_id)

class OCRTranscription(models.Model): # 20 fields for the user
    def __str__(self):
        return "OCR Transcription Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'OCR Transcription Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    ocr_1 = models.CharField(max_length=10)
    ocr_2 = models.CharField(max_length=10)
    ocr_3 = models.CharField(max_length=10)
    ocr_4 = models.CharField(max_length=10)
    ocr_5 = models.CharField(max_length=10)
    ocr_6 = models.CharField(max_length=10)
    ocr_7 = models.CharField(max_length=10)
    ocr_8 = models.CharField(max_length=10)
    ocr_9 = models.CharField(max_length=10)
    ocr_10 = models.CharField(max_length=10)
    ocr_11 = models.CharField(max_length=10)
    ocr_12 = models.CharField(max_length=10)
    ocr_13 = models.CharField(max_length=10)
    ocr_14 = models.CharField(max_length=10)
    ocr_15 = models.CharField(max_length=10)
    ocr_16 = models.CharField(max_length=10)
    ocr_17 = models.CharField(max_length=10)
    ocr_18 = models.CharField(max_length=10)


class OCRVerification(models.Model):
    def __str__(self):
        return "OCR Verification Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'OCR Verification Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    ocr_1 = models.BooleanField(default=False)
    ocr_2 = models.BooleanField(default=False)
    ocr_3 = models.BooleanField(default=False)
    ocr_4 = models.BooleanField(default=False)
    ocr_5 = models.BooleanField(default=False)
    ocr_6 = models.BooleanField(default=False)
    ocr_7 = models.BooleanField(default=False)
    ocr_8 = models.BooleanField(default=False)
    ocr_9 = models.BooleanField(default=False)
    ocr_10 = models.BooleanField(default=False)
    ocr_11 = models.BooleanField(default=False)
    ocr_12 = models.BooleanField(default=False)
    ocr_13 = models.BooleanField(default=False)
    ocr_14 = models.BooleanField(default=False)
    ocr_15 = models.BooleanField(default=False)
    ocr_16 = models.BooleanField(default=False)
    ocr_17 = models.BooleanField(default=False)
    ocr_18 = models.BooleanField(default=False)


class CrowdsourceVerification(models.Model):
    def __str__(self):
        return "Crowdsource Verification Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Crowdsource Verification Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    ocr_1 = models.BooleanField(default=False)
    ocr_2 = models.BooleanField(default=False)
    ocr_3 = models.BooleanField(default=False)
    ocr_4 = models.BooleanField(default=False)
    ocr_5 = models.BooleanField(default=False)
    ocr_6 = models.BooleanField(default=False)
    ocr_7 = models.BooleanField(default=False)
    ocr_8 = models.BooleanField(default=False)
    ocr_9 = models.BooleanField(default=False)
    ocr_10 = models.BooleanField(default=False)
    ocr_11 = models.BooleanField(default=False)
    ocr_12 = models.BooleanField(default=False)
    ocr_13 = models.BooleanField(default=False)
    ocr_14 = models.BooleanField(default=False)
    ocr_15 = models.BooleanField(default=False)
    ocr_16 = models.BooleanField(default=False)
    ocr_17 = models.BooleanField(default=False)
    ocr_18 = models.BooleanField(default=False)


class NamingTranscription1(models.Model):
    def __str__(self):
        return "Naming Transcription Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Naming Transcription Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    cell_b25 = models.CharField(max_length=10)
    confidence_b25 = models.PositiveIntegerField(default=5)
    cell_c25 = models.CharField(max_length=10)
    confidence_c25 = models.PositiveIntegerField(default=5)
    cell_d25 = models.CharField(max_length=10)
    confidence_d25 = models.PositiveIntegerField(default=5)
    cell_e25 = models.CharField(max_length=10)
    confidence_e25 = models.PositiveIntegerField(default=5)
    cell_f25 = models.CharField(max_length=10)
    confidence_f25 = models.PositiveIntegerField(default=5)
    cell_g25 = models.CharField(max_length=10)
    confidence_g25 = models.PositiveIntegerField(default=5)
    cell_h25 = models.CharField(max_length=10)
    confidence_h25 = models.PositiveIntegerField(default=5)
    cell_i25 = models.CharField(max_length=10)
    confidence_i25 = models.PositiveIntegerField(default=5)
    cell_b26 = models.CharField(max_length=10)
    confidence_b26 = models.PositiveIntegerField(default=5)
    cell_c26 = models.CharField(max_length=10)
    confidence_c26 = models.PositiveIntegerField(default=5)
    cell_d26 = models.CharField(max_length=10)
    confidence_d26 = models.PositiveIntegerField(default=5)
    cell_e26 = models.CharField(max_length=10)
    confidence_e26 = models.PositiveIntegerField(default=5)
    cell_f26 = models.CharField(max_length=10)
    confidence_f26 = models.PositiveIntegerField(default=5)
    cell_g26 = models.CharField(max_length=10)
    confidence_g26 = models.PositiveIntegerField(default=5)
    cell_h26 = models.CharField(max_length=10)
    confidence_h26 = models.PositiveIntegerField(default=5)
    cell_i26 = models.CharField(max_length=10)
    confidence_i26 = models.PositiveIntegerField(default=5)
    cell_b27 = models.CharField(max_length=10)
    confidence_b27 = models.PositiveIntegerField(default=5)
    cell_c27 = models.CharField(max_length=10)
    confidence_c27 = models.PositiveIntegerField(default=5)
    cell_d27 = models.CharField(max_length=10)
    confidence_d27 = models.PositiveIntegerField(default=5)
    cell_e27 = models.CharField(max_length=10)
    confidence_e27 = models.PositiveIntegerField(default=5)
    cell_f27 = models.CharField(max_length=10)
    confidence_f27 = models.PositiveIntegerField(default=5)
    cell_g27 = models.CharField(max_length=10)
    confidence_g27 = models.PositiveIntegerField(default=5)
    cell_h27 = models.CharField(max_length=10)
    confidence_h27 = models.PositiveIntegerField(default=5)
    cell_i27 = models.CharField(max_length=10)
    confidence_i27 = models.PositiveIntegerField(default=5)
    cell_b28 = models.CharField(max_length=10)
    confidence_b28 = models.PositiveIntegerField(default=5)
    cell_c28 = models.CharField(max_length=10)
    confidence_c28 = models.PositiveIntegerField(default=5)
    cell_d28 = models.CharField(max_length=10)
    confidence_d28 = models.PositiveIntegerField(default=5)
    cell_e28 = models.CharField(max_length=10)
    confidence_e28 = models.PositiveIntegerField(default=5)
    cell_f28 = models.CharField(max_length=10)
    confidence_f28 = models.PositiveIntegerField(default=5)
    cell_g28 = models.CharField(max_length=10)
    confidence_g28 = models.PositiveIntegerField(default=5)
    cell_h28 = models.CharField(max_length=10)
    confidence_h28 = models.PositiveIntegerField(default=5)
    cell_i28 = models.CharField(max_length=10)
    confidence_i28 = models.PositiveIntegerField(default=5)
    cell_b29 = models.CharField(max_length=10)
    confidence_b29 = models.PositiveIntegerField(default=5)
    cell_c29 = models.CharField(max_length=10)
    confidence_c29 = models.PositiveIntegerField(default=5)
    cell_d29 = models.CharField(max_length=10)
    confidence_d29 = models.PositiveIntegerField(default=5)
    cell_e29 = models.CharField(max_length=10)
    confidence_e29 = models.PositiveIntegerField(default=5)
    cell_f29 = models.CharField(max_length=10)
    confidence_f29 = models.PositiveIntegerField(default=5)
    cell_g29 = models.CharField(max_length=10)
    confidence_g29 = models.PositiveIntegerField(default=5)
    cell_h29 = models.CharField(max_length=10)
    confidence_h29 = models.PositiveIntegerField(default=5)
    cell_i29 = models.CharField(max_length=10)
    confidence_i29 = models.PositiveIntegerField(default=5)
    cell_b30 = models.CharField(max_length=10)
    confidence_b30 = models.PositiveIntegerField(default=5)
    cell_c30 = models.CharField(max_length=10)
    confidence_c30 = models.PositiveIntegerField(default=5)
    cell_d30 = models.CharField(max_length=10)
    confidence_d30 = models.PositiveIntegerField(default=5)
    cell_e30 = models.CharField(max_length=10)
    confidence_e30 = models.PositiveIntegerField(default=5)
    cell_f30 = models.CharField(max_length=10)
    confidence_f30 = models.PositiveIntegerField(default=5)
    cell_g30 = models.CharField(max_length=10)
    confidence_g30 = models.PositiveIntegerField(default=5)
    cell_h30 = models.CharField(max_length=10)
    confidence_h30 = models.PositiveIntegerField(default=5)
    cell_i30 = models.CharField(max_length=10)
    confidence_i30 = models.PositiveIntegerField(default=5)
    cell_b31 = models.CharField(max_length=10)
    confidence_b31 = models.PositiveIntegerField(default=5)
    cell_c31 = models.CharField(max_length=10)
    confidence_c31 = models.PositiveIntegerField(default=5)
    cell_d31 = models.CharField(max_length=10)
    confidence_d31 = models.PositiveIntegerField(default=5)
    cell_e31 = models.CharField(max_length=10)
    confidence_e31 = models.PositiveIntegerField(default=5)
    cell_f31 = models.CharField(max_length=10)
    confidence_f31 = models.PositiveIntegerField(default=5)
    cell_g31 = models.CharField(max_length=10)
    confidence_g31 = models.PositiveIntegerField(default=5)
    cell_h31 = models.CharField(max_length=10)
    confidence_h31 = models.PositiveIntegerField(default=5)
    cell_i31 = models.CharField(max_length=10)
    confidence_i31 = models.PositiveIntegerField(default=5)
    cell_b32 = models.CharField(max_length=10)
    confidence_b32 = models.PositiveIntegerField(default=5)
    cell_c32 = models.CharField(max_length=10)
    confidence_c32 = models.PositiveIntegerField(default=5)
    cell_d32 = models.CharField(max_length=10)
    confidence_d32 = models.PositiveIntegerField(default=5)
    cell_e32 = models.CharField(max_length=10)
    confidence_e32 = models.PositiveIntegerField(default=5)
    cell_f32 = models.CharField(max_length=10)
    confidence_f32 = models.PositiveIntegerField(default=5)
    cell_g32 = models.CharField(max_length=10)
    confidence_g32 = models.PositiveIntegerField(default=5)
    cell_h32 = models.CharField(max_length=10)
    confidence_h32 = models.PositiveIntegerField(default=5)
    cell_i32 = models.CharField(max_length=10)
    confidence_i32 = models.PositiveIntegerField(default=5)
    cell_b33 = models.CharField(max_length=10)
    confidence_b33 = models.PositiveIntegerField(default=5)
    cell_c33 = models.CharField(max_length=10)
    confidence_c33 = models.PositiveIntegerField(default=5)
    cell_d33 = models.CharField(max_length=10)
    confidence_d33 = models.PositiveIntegerField(default=5)
    cell_e33 = models.CharField(max_length=10)
    confidence_e33 = models.PositiveIntegerField(default=5)
    cell_f33 = models.CharField(max_length=10)
    confidence_f33 = models.PositiveIntegerField(default=5)
    cell_g33 = models.CharField(max_length=10)
    confidence_g33 = models.PositiveIntegerField(default=5)
    cell_h33 = models.CharField(max_length=10)
    confidence_h33 = models.PositiveIntegerField(default=5)
    cell_i33 = models.CharField(max_length=10)
    confidence_i33 = models.PositiveIntegerField(default=5)
    cell_b34 = models.CharField(max_length=10)
    confidence_b34 = models.PositiveIntegerField(default=5)
    cell_c34 = models.CharField(max_length=10)
    confidence_c34 = models.PositiveIntegerField(default=5)
    cell_d34 = models.CharField(max_length=10)
    confidence_d34 = models.PositiveIntegerField(default=5)
    cell_e34 = models.CharField(max_length=10)
    confidence_e34 = models.PositiveIntegerField(default=5)
    cell_f34 = models.CharField(max_length=10)
    confidence_f34 = models.PositiveIntegerField(default=5)
    cell_g34 = models.CharField(max_length=10)
    confidence_g34 = models.PositiveIntegerField(default=5)
    cell_h34 = models.CharField(max_length=10)
    confidence_h34 = models.PositiveIntegerField(default=5)
    cell_i34 = models.CharField(max_length=10)
    confidence_i34 = models.PositiveIntegerField(default=5)
    cell_b35 = models.CharField(max_length=10)
    confidence_b35 = models.PositiveIntegerField(default=5)
    cell_c35 = models.CharField(max_length=10)
    confidence_c35 = models.PositiveIntegerField(default=5)
    cell_d35 = models.CharField(max_length=10)
    confidence_d35 = models.PositiveIntegerField(default=5)
    cell_e35 = models.CharField(max_length=10)
    confidence_e35 = models.PositiveIntegerField(default=5)
    cell_f35 = models.CharField(max_length=10)
    confidence_f35 = models.PositiveIntegerField(default=5)
    cell_g35 = models.CharField(max_length=10)
    confidence_g35 = models.PositiveIntegerField(default=5)
    cell_h35 = models.CharField(max_length=10)
    confidence_h35 = models.PositiveIntegerField(default=5)
    cell_i35 = models.CharField(max_length=10)
    confidence_i35 = models.PositiveIntegerField(default=5)
    cell_b36 = models.CharField(max_length=10)
    confidence_b36 = models.PositiveIntegerField(default=5)
    cell_c36 = models.CharField(max_length=10)
    confidence_c36 = models.PositiveIntegerField(default=5)
    cell_d36 = models.CharField(max_length=10)
    confidence_d36 = models.PositiveIntegerField(default=5)
    cell_e36 = models.CharField(max_length=10)
    confidence_e36 = models.PositiveIntegerField(default=5)
    cell_f36 = models.CharField(max_length=10)
    confidence_f36 = models.PositiveIntegerField(default=5)
    cell_g36 = models.CharField(max_length=10)
    confidence_g36 = models.PositiveIntegerField(default=5)
    cell_h36 = models.CharField(max_length=10)
    confidence_h36 = models.PositiveIntegerField(default=5)
    cell_i36 = models.CharField(max_length=10)
    confidence_i36 = models.PositiveIntegerField(default=5)
    cell_b37 = models.CharField(max_length=10)
    confidence_b37 = models.PositiveIntegerField(default=5)
    cell_c37 = models.CharField(max_length=10)
    confidence_c37 = models.PositiveIntegerField(default=5)
    cell_d37 = models.CharField(max_length=10)
    confidence_d37 = models.PositiveIntegerField(default=5)
    cell_e37 = models.CharField(max_length=10)
    confidence_e37 = models.PositiveIntegerField(default=5)
    cell_f37 = models.CharField(max_length=10)
    confidence_f37 = models.PositiveIntegerField(default=5)
    cell_g37 = models.CharField(max_length=10)
    confidence_g37 = models.PositiveIntegerField(default=5)
    cell_h37 = models.CharField(max_length=10)
    confidence_h37 = models.PositiveIntegerField(default=5)
    cell_i37 = models.CharField(max_length=10)
    confidence_i37 = models.PositiveIntegerField(default=5)
    cell_b38 = models.CharField(max_length=10)
    confidence_b38 = models.PositiveIntegerField(default=5)
    cell_c38 = models.CharField(max_length=10)
    confidence_c38 = models.PositiveIntegerField(default=5)
    cell_d38 = models.CharField(max_length=10)
    confidence_d38 = models.PositiveIntegerField(default=5)
    cell_e38 = models.CharField(max_length=10)
    confidence_e38 = models.PositiveIntegerField(default=5)
    cell_f38 = models.CharField(max_length=10)
    confidence_f38 = models.PositiveIntegerField(default=5)
    cell_g38 = models.CharField(max_length=10)
    confidence_g38 = models.PositiveIntegerField(default=5)
    cell_h38 = models.CharField(max_length=10)
    confidence_h38 = models.PositiveIntegerField(default=5)
    cell_i38 = models.CharField(max_length=10)
    confidence_i38 = models.PositiveIntegerField(default=5)
    cell_b39 = models.CharField(max_length=10)
    confidence_b39 = models.PositiveIntegerField(default=5)
    cell_c39 = models.CharField(max_length=10)
    confidence_c39 = models.PositiveIntegerField(default=5)
    cell_d39 = models.CharField(max_length=10)
    confidence_d39 = models.PositiveIntegerField(default=5)
    cell_e39 = models.CharField(max_length=10)
    confidence_e39 = models.PositiveIntegerField(default=5)
    cell_f39 = models.CharField(max_length=10)
    confidence_f39 = models.PositiveIntegerField(default=5)
    cell_g39 = models.CharField(max_length=10)
    confidence_g39 = models.PositiveIntegerField(default=5)
    cell_h39 = models.CharField(max_length=10)
    confidence_h39 = models.PositiveIntegerField(default=5)
    cell_i39 = models.CharField(max_length=10)
    confidence_i39 = models.PositiveIntegerField(default=5)
    cell_b40 = models.CharField(max_length=10)
    confidence_b40 = models.PositiveIntegerField(default=5)
    cell_c40 = models.CharField(max_length=10)
    confidence_c40 = models.PositiveIntegerField(default=5)
    cell_d40 = models.CharField(max_length=10)
    confidence_d40 = models.PositiveIntegerField(default=5)
    cell_e40 = models.CharField(max_length=10)
    confidence_e40 = models.PositiveIntegerField(default=5)
    cell_f40 = models.CharField(max_length=10)
    confidence_f40 = models.PositiveIntegerField(default=5)
    cell_g40 = models.CharField(max_length=10)
    confidence_g40 = models.PositiveIntegerField(default=5)
    cell_h40 = models.CharField(max_length=10)
    confidence_h40 = models.PositiveIntegerField(default=5)
    cell_i40 = models.CharField(max_length=10)
    confidence_i40 = models.PositiveIntegerField(default=5)


class NamingTranscription2(models.Model):
    def __str__(self):
        return "Naming Transcription (with key) Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Naming Transcription (key) Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    cell_b25 = models.CharField(max_length=10)
    confidence_b25 = models.PositiveIntegerField(default=5)
    cell_c25 = models.CharField(max_length=10)
    confidence_c25 = models.PositiveIntegerField(default=5)
    cell_d25 = models.CharField(max_length=10)
    confidence_d25 = models.PositiveIntegerField(default=5)
    cell_e25 = models.CharField(max_length=10)
    confidence_e25 = models.PositiveIntegerField(default=5)
    cell_f25 = models.CharField(max_length=10)
    confidence_f25 = models.PositiveIntegerField(default=5)
    cell_g25 = models.CharField(max_length=10)
    confidence_g25 = models.PositiveIntegerField(default=5)
    cell_h25 = models.CharField(max_length=10)
    confidence_h25 = models.PositiveIntegerField(default=5)
    cell_i25 = models.CharField(max_length=10)
    confidence_i25 = models.PositiveIntegerField(default=5)
    cell_b26 = models.CharField(max_length=10)
    confidence_b26 = models.PositiveIntegerField(default=5)
    cell_c26 = models.CharField(max_length=10)
    confidence_c26 = models.PositiveIntegerField(default=5)
    cell_d26 = models.CharField(max_length=10)
    confidence_d26 = models.PositiveIntegerField(default=5)
    cell_e26 = models.CharField(max_length=10)
    confidence_e26 = models.PositiveIntegerField(default=5)
    cell_f26 = models.CharField(max_length=10)
    confidence_f26 = models.PositiveIntegerField(default=5)
    cell_g26 = models.CharField(max_length=10)
    confidence_g26 = models.PositiveIntegerField(default=5)
    cell_h26 = models.CharField(max_length=10)
    confidence_h26 = models.PositiveIntegerField(default=5)
    cell_i26 = models.CharField(max_length=10)
    confidence_i26 = models.PositiveIntegerField(default=5)
    cell_b27 = models.CharField(max_length=10)
    confidence_b27 = models.PositiveIntegerField(default=5)
    cell_c27 = models.CharField(max_length=10)
    confidence_c27 = models.PositiveIntegerField(default=5)
    cell_d27 = models.CharField(max_length=10)
    confidence_d27 = models.PositiveIntegerField(default=5)
    cell_e27 = models.CharField(max_length=10)
    confidence_e27 = models.PositiveIntegerField(default=5)
    cell_f27 = models.CharField(max_length=10)
    confidence_f27 = models.PositiveIntegerField(default=5)
    cell_g27 = models.CharField(max_length=10)
    confidence_g27 = models.PositiveIntegerField(default=5)
    cell_h27 = models.CharField(max_length=10)
    confidence_h27 = models.PositiveIntegerField(default=5)
    cell_i27 = models.CharField(max_length=10)
    confidence_i27 = models.PositiveIntegerField(default=5)
    cell_b28 = models.CharField(max_length=10)
    confidence_b28 = models.PositiveIntegerField(default=5)
    cell_c28 = models.CharField(max_length=10)
    confidence_c28 = models.PositiveIntegerField(default=5)
    cell_d28 = models.CharField(max_length=10)
    confidence_d28 = models.PositiveIntegerField(default=5)
    cell_e28 = models.CharField(max_length=10)
    confidence_e28 = models.PositiveIntegerField(default=5)
    cell_f28 = models.CharField(max_length=10)
    confidence_f28 = models.PositiveIntegerField(default=5)
    cell_g28 = models.CharField(max_length=10)
    confidence_g28 = models.PositiveIntegerField(default=5)
    cell_h28 = models.CharField(max_length=10)
    confidence_h28 = models.PositiveIntegerField(default=5)
    cell_i28 = models.CharField(max_length=10)
    confidence_i28 = models.PositiveIntegerField(default=5)
    cell_b29 = models.CharField(max_length=10)
    confidence_b29 = models.PositiveIntegerField(default=5)
    cell_c29 = models.CharField(max_length=10)
    confidence_c29 = models.PositiveIntegerField(default=5)
    cell_d29 = models.CharField(max_length=10)
    confidence_d29 = models.PositiveIntegerField(default=5)
    cell_e29 = models.CharField(max_length=10)
    confidence_e29 = models.PositiveIntegerField(default=5)
    cell_f29 = models.CharField(max_length=10)
    confidence_f29 = models.PositiveIntegerField(default=5)
    cell_g29 = models.CharField(max_length=10)
    confidence_g29 = models.PositiveIntegerField(default=5)
    cell_h29 = models.CharField(max_length=10)
    confidence_h29 = models.PositiveIntegerField(default=5)
    cell_i29 = models.CharField(max_length=10)
    confidence_i29 = models.PositiveIntegerField(default=5)
    cell_b30 = models.CharField(max_length=10)
    confidence_b30 = models.PositiveIntegerField(default=5)
    cell_c30 = models.CharField(max_length=10)
    confidence_c30 = models.PositiveIntegerField(default=5)
    cell_d30 = models.CharField(max_length=10)
    confidence_d30 = models.PositiveIntegerField(default=5)
    cell_e30 = models.CharField(max_length=10)
    confidence_e30 = models.PositiveIntegerField(default=5)
    cell_f30 = models.CharField(max_length=10)
    confidence_f30 = models.PositiveIntegerField(default=5)
    cell_g30 = models.CharField(max_length=10)
    confidence_g30 = models.PositiveIntegerField(default=5)
    cell_h30 = models.CharField(max_length=10)
    confidence_h30 = models.PositiveIntegerField(default=5)
    cell_i30 = models.CharField(max_length=10)
    confidence_i30 = models.PositiveIntegerField(default=5)
    cell_b31 = models.CharField(max_length=10)
    confidence_b31 = models.PositiveIntegerField(default=5)
    cell_c31 = models.CharField(max_length=10)
    confidence_c31 = models.PositiveIntegerField(default=5)
    cell_d31 = models.CharField(max_length=10)
    confidence_d31 = models.PositiveIntegerField(default=5)
    cell_e31 = models.CharField(max_length=10)
    confidence_e31 = models.PositiveIntegerField(default=5)
    cell_f31 = models.CharField(max_length=10)
    confidence_f31 = models.PositiveIntegerField(default=5)
    cell_g31 = models.CharField(max_length=10)
    confidence_g31 = models.PositiveIntegerField(default=5)
    cell_h31 = models.CharField(max_length=10)
    confidence_h31 = models.PositiveIntegerField(default=5)
    cell_i31 = models.CharField(max_length=10)
    confidence_i31 = models.PositiveIntegerField(default=5)
    cell_b32 = models.CharField(max_length=10)
    confidence_b32 = models.PositiveIntegerField(default=5)
    cell_c32 = models.CharField(max_length=10)
    confidence_c32 = models.PositiveIntegerField(default=5)
    cell_d32 = models.CharField(max_length=10)
    confidence_d32 = models.PositiveIntegerField(default=5)
    cell_e32 = models.CharField(max_length=10)
    confidence_e32 = models.PositiveIntegerField(default=5)
    cell_f32 = models.CharField(max_length=10)
    confidence_f32 = models.PositiveIntegerField(default=5)
    cell_g32 = models.CharField(max_length=10)
    confidence_g32 = models.PositiveIntegerField(default=5)
    cell_h32 = models.CharField(max_length=10)
    confidence_h32 = models.PositiveIntegerField(default=5)
    cell_i32 = models.CharField(max_length=10)
    confidence_i32 = models.PositiveIntegerField(default=5)
    cell_b33 = models.CharField(max_length=10)
    confidence_b33 = models.PositiveIntegerField(default=5)
    cell_c33 = models.CharField(max_length=10)
    confidence_c33 = models.PositiveIntegerField(default=5)
    cell_d33 = models.CharField(max_length=10)
    confidence_d33 = models.PositiveIntegerField(default=5)
    cell_e33 = models.CharField(max_length=10)
    confidence_e33 = models.PositiveIntegerField(default=5)
    cell_f33 = models.CharField(max_length=10)
    confidence_f33 = models.PositiveIntegerField(default=5)
    cell_g33 = models.CharField(max_length=10)
    confidence_g33 = models.PositiveIntegerField(default=5)
    cell_h33 = models.CharField(max_length=10)
    confidence_h33 = models.PositiveIntegerField(default=5)
    cell_i33 = models.CharField(max_length=10)
    confidence_i33 = models.PositiveIntegerField(default=5)
    cell_b34 = models.CharField(max_length=10)
    confidence_b34 = models.PositiveIntegerField(default=5)
    cell_c34 = models.CharField(max_length=10)
    confidence_c34 = models.PositiveIntegerField(default=5)
    cell_d34 = models.CharField(max_length=10)
    confidence_d34 = models.PositiveIntegerField(default=5)
    cell_e34 = models.CharField(max_length=10)
    confidence_e34 = models.PositiveIntegerField(default=5)
    cell_f34 = models.CharField(max_length=10)
    confidence_f34 = models.PositiveIntegerField(default=5)
    cell_g34 = models.CharField(max_length=10)
    confidence_g34 = models.PositiveIntegerField(default=5)
    cell_h34 = models.CharField(max_length=10)
    confidence_h34 = models.PositiveIntegerField(default=5)
    cell_i34 = models.CharField(max_length=10)
    confidence_i34 = models.PositiveIntegerField(default=5)
    cell_b35 = models.CharField(max_length=10)
    confidence_b35 = models.PositiveIntegerField(default=5)
    cell_c35 = models.CharField(max_length=10)
    confidence_c35 = models.PositiveIntegerField(default=5)
    cell_d35 = models.CharField(max_length=10)
    confidence_d35 = models.PositiveIntegerField(default=5)
    cell_e35 = models.CharField(max_length=10)
    confidence_e35 = models.PositiveIntegerField(default=5)
    cell_f35 = models.CharField(max_length=10)
    confidence_f35 = models.PositiveIntegerField(default=5)
    cell_g35 = models.CharField(max_length=10)
    confidence_g35 = models.PositiveIntegerField(default=5)
    cell_h35 = models.CharField(max_length=10)
    confidence_h35 = models.PositiveIntegerField(default=5)
    cell_i35 = models.CharField(max_length=10)
    confidence_i35 = models.PositiveIntegerField(default=5)
    cell_b36 = models.CharField(max_length=10)
    confidence_b36 = models.PositiveIntegerField(default=5)
    cell_c36 = models.CharField(max_length=10)
    confidence_c36 = models.PositiveIntegerField(default=5)
    cell_d36 = models.CharField(max_length=10)
    confidence_d36 = models.PositiveIntegerField(default=5)
    cell_e36 = models.CharField(max_length=10)
    confidence_e36 = models.PositiveIntegerField(default=5)
    cell_f36 = models.CharField(max_length=10)
    confidence_f36 = models.PositiveIntegerField(default=5)
    cell_g36 = models.CharField(max_length=10)
    confidence_g36 = models.PositiveIntegerField(default=5)
    cell_h36 = models.CharField(max_length=10)
    confidence_h36 = models.PositiveIntegerField(default=5)
    cell_i36 = models.CharField(max_length=10)
    confidence_i36 = models.PositiveIntegerField(default=5)
    cell_b37 = models.CharField(max_length=10)
    confidence_b37 = models.PositiveIntegerField(default=5)
    cell_c37 = models.CharField(max_length=10)
    confidence_c37 = models.PositiveIntegerField(default=5)
    cell_d37 = models.CharField(max_length=10)
    confidence_d37 = models.PositiveIntegerField(default=5)
    cell_e37 = models.CharField(max_length=10)
    confidence_e37 = models.PositiveIntegerField(default=5)
    cell_f37 = models.CharField(max_length=10)
    confidence_f37 = models.PositiveIntegerField(default=5)
    cell_g37 = models.CharField(max_length=10)
    confidence_g37 = models.PositiveIntegerField(default=5)
    cell_h37 = models.CharField(max_length=10)
    confidence_h37 = models.PositiveIntegerField(default=5)
    cell_i37 = models.CharField(max_length=10)
    confidence_i37 = models.PositiveIntegerField(default=5)
    cell_b38 = models.CharField(max_length=10)
    confidence_b38 = models.PositiveIntegerField(default=5)
    cell_c38 = models.CharField(max_length=10)
    confidence_c38 = models.PositiveIntegerField(default=5)
    cell_d38 = models.CharField(max_length=10)
    confidence_d38 = models.PositiveIntegerField(default=5)
    cell_e38 = models.CharField(max_length=10)
    confidence_e38 = models.PositiveIntegerField(default=5)
    cell_f38 = models.CharField(max_length=10)
    confidence_f38 = models.PositiveIntegerField(default=5)
    cell_g38 = models.CharField(max_length=10)
    confidence_g38 = models.PositiveIntegerField(default=5)
    cell_h38 = models.CharField(max_length=10)
    confidence_h38 = models.PositiveIntegerField(default=5)
    cell_i38 = models.CharField(max_length=10)
    confidence_i38 = models.PositiveIntegerField(default=5)
    cell_b39 = models.CharField(max_length=10)
    confidence_b39 = models.PositiveIntegerField(default=5)
    cell_c39 = models.CharField(max_length=10)
    confidence_c39 = models.PositiveIntegerField(default=5)
    cell_d39 = models.CharField(max_length=10)
    confidence_d39 = models.PositiveIntegerField(default=5)
    cell_e39 = models.CharField(max_length=10)
    confidence_e39 = models.PositiveIntegerField(default=5)
    cell_f39 = models.CharField(max_length=10)
    confidence_f39 = models.PositiveIntegerField(default=5)
    cell_g39 = models.CharField(max_length=10)
    confidence_g39 = models.PositiveIntegerField(default=5)
    cell_h39 = models.CharField(max_length=10)
    confidence_h39 = models.PositiveIntegerField(default=5)
    cell_i39 = models.CharField(max_length=10)
    confidence_i39 = models.PositiveIntegerField(default=5)
    cell_b40 = models.CharField(max_length=10)
    confidence_b40 = models.PositiveIntegerField(default=5)
    cell_c40 = models.CharField(max_length=10)
    confidence_c40 = models.PositiveIntegerField(default=5)
    cell_d40 = models.CharField(max_length=10)
    confidence_d40 = models.PositiveIntegerField(default=5)
    cell_e40 = models.CharField(max_length=10)
    confidence_e40 = models.PositiveIntegerField(default=5)
    cell_f40 = models.CharField(max_length=10)
    confidence_f40 = models.PositiveIntegerField(default=5)
    cell_g40 = models.CharField(max_length=10)
    confidence_g40 = models.PositiveIntegerField(default=5)
    cell_h40 = models.CharField(max_length=10)
    confidence_h40 = models.PositiveIntegerField(default=5)
    cell_i40 = models.CharField(max_length=10)
    confidence_i40 = models.PositiveIntegerField(default=5)


class FociTranscription1(models.Model):
    def __str__(self):
        return "Foci Transcription Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Foci Transcription Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    value_1 = models.CharField(max_length=10)
    row_1 = models.CharField(max_length=10)
    column_1 = models.CharField(max_length=10)
    confidence_1 = models.PositiveIntegerField(default=5)
    value_2 = models.CharField(max_length=10)
    row_2 = models.CharField(max_length=10)
    column_2 = models.CharField(max_length=10)
    confidence_2 = models.PositiveIntegerField(default=5)
    value_3 = models.CharField(max_length=10)
    row_3 = models.CharField(max_length=10)
    column_3 = models.CharField(max_length=10)
    confidence_3 = models.PositiveIntegerField(default=5)
    value_4 = models.CharField(max_length=10)
    row_4 = models.CharField(max_length=10)
    column_4 = models.CharField(max_length=10)
    confidence_4 = models.PositiveIntegerField(default=5)
    value_5 = models.CharField(max_length=10)
    row_5 = models.CharField(max_length=10)
    column_5 = models.CharField(max_length=10)
    confidence_5 = models.PositiveIntegerField(default=5)
    value_6 = models.CharField(max_length=10)
    row_6 = models.CharField(max_length=10)
    column_6 = models.CharField(max_length=10)
    confidence_6 = models.PositiveIntegerField(default=5)
    value_7 = models.CharField(max_length=10)
    row_7 = models.CharField(max_length=10)
    column_7 = models.CharField(max_length=10)
    confidence_7 = models.PositiveIntegerField(default=5)
    value_8 = models.CharField(max_length=10)
    row_8 = models.CharField(max_length=10)
    column_8 = models.CharField(max_length=10)
    confidence_8 = models.PositiveIntegerField(default=5)
    value_9 = models.CharField(max_length=10)
    row_9 = models.CharField(max_length=10)
    column_9 = models.CharField(max_length=10)
    confidence_9 = models.PositiveIntegerField(default=5)
    value_10 = models.CharField(max_length=10)
    row_10 = models.CharField(max_length=10)
    column_10 = models.CharField(max_length=10)
    confidence_10 = models.PositiveIntegerField(default=5)

class FociTranscription2(models.Model):
    def __str__(self):
        return "Foci Transcription (with key) Response #" + str(self.response_id)
    class Meta:
        verbose_name = 'Foci Transcription (key) Response'

    response_id = models.AutoField(primary_key=True, unique=True)
    user = models.CharField(max_length=30)
    value_1 = models.CharField(max_length=10)
    row_1 = models.CharField(max_length=10)
    column_1 = models.CharField(max_length=10)
    confidence_1 = models.PositiveIntegerField(default=5)
    value_2 = models.CharField(max_length=10)
    row_2 = models.CharField(max_length=10)
    column_2 = models.CharField(max_length=10)
    confidence_2 = models.PositiveIntegerField(default=5)
    value_3 = models.CharField(max_length=10)
    row_3 = models.CharField(max_length=10)
    column_3 = models.CharField(max_length=10)
    confidence_3 = models.PositiveIntegerField(default=5)
    value_4 = models.CharField(max_length=10)
    row_4 = models.CharField(max_length=10)
    column_4 = models.CharField(max_length=10)
    confidence_4 = models.PositiveIntegerField(default=5)
    value_5 = models.CharField(max_length=10)
    row_5 = models.CharField(max_length=10)
    column_5 = models.CharField(max_length=10)
    confidence_5 = models.PositiveIntegerField(default=5)
    value_6 = models.CharField(max_length=10)
    row_6 = models.CharField(max_length=10)
    column_6 = models.CharField(max_length=10)
    confidence_6 = models.PositiveIntegerField(default=5)
    value_7 = models.CharField(max_length=10)
    row_7 = models.CharField(max_length=10)
    column_7 = models.CharField(max_length=10)
    confidence_7 = models.PositiveIntegerField(default=5)
    value_8 = models.CharField(max_length=10)
    row_8 = models.CharField(max_length=10)
    column_8 = models.CharField(max_length=10)
    confidence_8 = models.PositiveIntegerField(default=5)
    value_9 = models.CharField(max_length=10)
    row_9 = models.CharField(max_length=10)
    column_9 = models.CharField(max_length=10)
    confidence_9 = models.PositiveIntegerField(default=5)
    value_10 = models.CharField(max_length=10)
    row_10 = models.CharField(max_length=10)
    column_10 = models.CharField(max_length=10)
    confidence_10 = models.PositiveIntegerField(default=5)


# class FociGridTranscription1(models.Model):
#     def __str__(self):
#         return "Foci Grid Transcription Response #" + str(self.response_id)
#     class Meta:
#         verbose_name = 'Foci Grid Transcription Response'
#
#     response_id = models.AutoField(primary_key=True, unique=True)
#     user = models.CharField(max_length=30)
#
#
# class FociGridTranscription1(models.Model):
#     def __str__(self):
#         return "Foci Grid Transcription Response #" + str(self.response_id)
#     class Meta:
#         verbose_name = 'Foci Grid Transcription (key) Response'
#
#     response_id = models.AutoField(primary_key=True, unique=True)
#     user = models.CharField(max_length=30)
